(defun my-goto-favorite-1 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 1)
    (message "my-goto-favorite #1 is not implemented")))
(global-set-key (kbd "s-1") 'my-goto-favorite-1)

(defun my-goto-favorite-2 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 2)
    (message "my-goto-favorite #2 is not implemented")))
(global-set-key (kbd "s-2") 'my-goto-favorite-2)

(defun my-goto-favorite-3 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 3)
    (message "my-goto-favorite #3 is not implemented")))
(global-set-key (kbd "s-3") 'my-goto-favorite-3)

(defun my-goto-favorite-4 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 4)
    (message "my-goto-favorite #4 is not implemented")))
(global-set-key (kbd "s-4") 'my-goto-favorite-4)

(defun my-goto-favorite-5 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 5)
    (message "my-goto-favorite #5 is not implemented")))
(global-set-key (kbd "s-5") 'my-goto-favorite-5)

(defun my-goto-favorite-6 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 6)
    (message "my-goto-favorite #6 is not implemented")))
(global-set-key (kbd "s-6") 'my-goto-favorite-6)

(defun my-goto-favorite-7 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 7)
    (message "my-goto-favorite #7 is not implemented")))
(global-set-key (kbd "s-7") 'my-goto-favorite-7)

(defun my-goto-favorite-8 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 8)
    (message "my-goto-favorite #8 is not implemented")))
(global-set-key (kbd "s-8") 'my-goto-favorite-8)

(defun my-goto-favorite-9 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 9)
    (message "my-goto-favorite #9 is not implemented")))
(global-set-key (kbd "s-9") 'my-goto-favorite-9)

(defun my-goto-favorite-10 ()
  (interactive)
  (if (fboundp 'my-goto-favorite)
    (my-goto-favorite 10)
    (message "my-goto-favorite #10 is not implemented")))
(global-set-key (kbd "s-0") 'my-goto-favorite-10)

