(global-set-key (kbd "C-S-f") (lambda (string)
  (interactive (list (read-from-minibuffer
    (concat "Search in "
            (if (and (boundp 'my-solution-grep-prev-filter)
                     (stringp my-solution-grep-prev-filter)
                     (not (string= my-solution-grep-prev-filter "")))
               my-solution-grep-prev-filter
              "all files")
            (if (and (boundp 'my-solution-grep-prev-vanilla-string)
                     (stringp my-solution-grep-prev-vanilla-string)
                     (not (string= my-solution-grep-prev-vanilla-string "")))
              (concat " (default " my-solution-grep-prev-vanilla-string ")")
              "")
            ": "))))
  (if (fboundp 'my-search-string-in-solution)
    (my-search-string-in-solution string)
    (message "my-search-string-in-solution is not implemented"))))

(global-set-key (kbd "C-S-M-f") (lambda (string)
  (interactive (list (read-from-minibuffer
    (concat "Search regexp in "
            (if (and (boundp 'my-solution-grep-prev-filter)
                     (stringp my-solution-grep-prev-filter)
                     (not (string= my-solution-grep-prev-filter "")))
              (concat my-solution-grep-prev-filter)
              "all files")
            (if (and (boundp 'my-solution-grep-prev-regex-string)
                     (stringp my-solution-grep-prev-regex-string)
                     (not (string= my-solution-grep-prev-regex-string "")))
              (concat " (default " my-solution-grep-prev-regex-string ")")
              "")
            ": "))))
  (if (fboundp 'my-search-regexp-in-solution)
    (my-search-regexp-in-solution string)
    (message "my-search-regexp-in-solution is not implemented"))))
