(global-set-key (kbd "C-S-g") (lambda ()
  (interactive)
  (if (fboundp 'my-commit-project)
    (my-commit-project (current-buffer))
    (message "my-commit-project is not implemented"))))

(global-set-key (kbd "C-S-l") (lambda ()
  (interactive)
  (if (fboundp 'my-logall-project)
    (my-logall-project (current-buffer))
    (message "my-logall-project is not implemented"))))

(global-set-key (kbd "s-L") (lambda ()
  (interactive)
  (if (fboundp 'my-logthis-project)
    (my-logthis-project (current-buffer))
    (message "my-logthis-project is not implemented"))))

(global-set-key (kbd "C-S-o") (lambda ()
  (interactive)
  (if (fboundp 'my-pull-project)
    (my-pull-project (current-buffer))
    (message "my-pull-project is not implemented"))))

(global-set-key (kbd "C-S-p") (lambda ()
  (interactive)
  (if (fboundp 'my-push-project)
    (my-push-project (current-buffer))
    (message "my-push-project is not implemented"))))
