;; todo. this does not work. why?!
;;(set (make-local-variable 'sbt-invokeXXX) YYY)
(if (not (boundp 'sbt-invoke-project)) (setq sbt-invoke-project (make-hash-table)))
(defun sbt-invoke-project () (gethash (buffer-name) sbt-invoke-project))
(defun set-sbt-invoke-project (value) (puthash (buffer-name) value sbt-invoke-project))
(if (not (boundp 'sbt-invoke-command)) (setq sbt-invoke-command (make-hash-table)))
(defun sbt-invoke-command () (gethash (buffer-name) sbt-invoke-command))
(defun set-sbt-invoke-command (value) (puthash (buffer-name) value sbt-invoke-command))

(defun sbt-invoke (buffer-name project command)
  (when (and buffer-name project)
    (let ((target-buffer (get-buffer buffer-name)))
    (if target-buffer (kill-buffer target-buffer))
    (setq target-buffer (get-buffer-create buffer-name))
    (set-buffer target-buffer)
    
    ;; todo. this does not work. why?!
    ;;(set (make-local-variable 'sbt-invoke-project) project)
    ;;(set (make-local-variable 'sbt-invoke-project) command)
    (set-sbt-invoke-project project)
    (set-sbt-invoke-command command)

    (let ((target-window 
      (cond 
        ((and (boundp 'tool-buffers-display-in-bottom-window) tool-buffers-display-in-bottom-window)
         (if (top-window) (active-window)
         (if (bottom-window) (bottom-window) 
         (split-window-vertically))))
        ((and (boundp 'tool-buffers-display-in-right-window) tool-buffers-display-in-right-window)
         (if (left-window) (left-window)
         (if (right-window) (right-window) 
         (split-window-horizontally))))
        (t
         (active-window)))))
    (let ((pop-up-windows t)) (set-window-buffer target-window target-buffer))
    (select-window target-window)))

    (comint-mode)
    (set (make-local-variable 'comint-process-echoes) t)
    (set (make-local-variable 'comint-scroll-to-bottom-on-output) t)
    (set (make-local-variable 'comint-prompt-read-only) t)
    (set (make-local-variable 'ansi-color-for-comint-mode) t)
    (set (make-local-variable 'comint-output-index) 0)
    (set (make-local-variable 'comint-output-history) "")

    (set (make-local-variable 'compilation-error-regexp-alist)
         '(("^\\([_.a-zA-Z0-9 :\\\\/-]+[.]n\\):\\([0-9]+\\):\\([0-9]+\\):\\([0-9]+\\):\\([0-9]+\\):"
            1 2 nil 2 nil)))
    (compilation-shell-minor-mode t)

    (defvar sbt-invoke-minor-mode-map (make-keymap) "sbt-invoke-minor-mode keymap.")
    (define-key sbt-invoke-minor-mode-map (kbd "<tab>") 'compilation-next-error)
    (define-key sbt-invoke-minor-mode-map (kbd "<backtab>") 'compilation-previous-error)
    (define-key sbt-invoke-minor-mode-map (kbd "<return>") (lambda ()
      (interactive)
      (if (and (get-buffer-process (current-buffer)) (eq (point) (point-max)))
        (comint-send-input)
        (compile-goto-error))))
    (define-key sbt-invoke-minor-mode-map (kbd "C-S-r") (lambda () (interactive) (my-repl-project (sbt-invoke-project))))
    (define-key sbt-invoke-minor-mode-map (kbd "C-S-b") (lambda () (interactive) (my-compile-project (sbt-invoke-project))))
    (define-prefix-command 'sbt-invoke-minor-mode-compile-map)
    (define-key sbt-invoke-minor-mode-map (kbd "M-b") 'sbt-invoke-minor-mode-compile-map)
    (define-key sbt-invoke-minor-mode-compile-map (kbd "r") (lambda () (interactive) (my-rebuild-project (sbt-invoke-project))))
    (define-key sbt-invoke-minor-mode-compile-map (kbd "M-r") (lambda () (interactive) (my-rebuild-project (sbt-invoke-project))))
    (define-key sbt-invoke-minor-mode-map (kbd "<C-S-return>") (lambda () (interactive) (my-run-project (sbt-invoke-project))))
    (define-key sbt-invoke-minor-mode-map (kbd "<s-S-return>") (lambda () (interactive) (my-test-project (sbt-invoke-project))))
    (define-key sbt-invoke-minor-mode-map (kbd "q") (lambda () 
      (interactive)
      (if (and (get-buffer-process (current-buffer)) (eq (point) (point-max)))
        (insert "q")
        (bury-buffer))))
    (define-key sbt-invoke-minor-mode-map (kbd "g") (lambda () 
      (interactive)
      (if (and (get-buffer-process (current-buffer)) (eq (point) (point-max)))
        (insert "g")
        (sbt-invoke (buffer-name) (sbt-invoke-project) (sbt-invoke-command)))))
    (define-minor-mode sbt-invoke-minor-mode "Hosts keybindings for nemerle compilation interactions" nil " sbt-invoke" 'sbt-invoke-minor-mode-map :global nil)
    (sbt-invoke-minor-mode 1)
    (defun my-minibuffer-setup-hook () (sbt-invoke-minor-mode 0))
    (add-hook 'minibuffer-setup-hook 'my-minibuffer-setup-hook)

    (cd (project-path (sbt-invoke-project)))
    (comint-exec (current-buffer) "bash" "bash" nil (list "-c" (concat (project-path (sbt-invoke-project)) "/" "sbt.sh " (sbt-invoke-command))))))

(defadvice recompile (around override-recompile-for-console activate)
  (if (sbt-invoke-project)
    (sbt-invoke (buffer-name) (sbt-invoke-project) (sbt-invoke-command))
    ad-do-it))

(defadvice revert-buffer (around override-revert-for-sbt activate)
  (if (sbt-invoke-project)
    (sbt-invoke (buffer-name) (sbt-invoke-project) (sbt-invoke-command))
    ad-do-it))

;; no need to advice kill-buffer since it calls bury-buffer internally
(defadvice bury-buffer (around auto-kill-dedicated-sbt-invoke-window-on-bury activate)
  (let ((sbt-invoke-project (sbt-invoke-project)))
  (let ((sole-window (sole-window)))
    (when sbt-invoke-project
      (when (not sole-window)
        (delete-window))
      (when sole-window 
        ad-do-it))
    (when (not sbt-invoke-project)
      ad-do-it))))
