(add-project "scratchpad" "/media/XENO/Dropbox/Projects/Foundations of Software/Scratchpad/src" "scratchpad" "scratchpad")
(add-project "nb" "/media/XENO/Dropbox/Projects/Foundations of Software/P1 - Numbers and Booleans/src" "nb" "nb")
(add-project "untyped" "/media/XENO/Dropbox/Projects/Foundations of Software/P2 - Untyped Lambda Calculus/src" "untyped" "untyped")
(add-project "typed" "/media/XENO/Dropbox/Projects/Foundations of Software/P3 - Typed Lambda Calculus/src" "typed" "typed")
(add-project "typedx" "/media/XENO/Dropbox/Projects/Foundations of Software/P4 - Typed Lambda Calculus Extensions/src" "typedx" "typedx")
(add-project "inference" "/media/XENO/Dropbox/Projects/Foundations of Software/P5 - Simply Typed Lambda Calculus with Type Reconstruction" "inference" "inference")
(add-project "fj" "/media/XENO/Dropbox/Projects/Foundations of Software/P6 - Featherweight Java" "fj" "fj")
(add-project "documents" "/media/XENO/Dropbox/Projects/Foundations of Software/Documents" nil)
(add-project "desktop" "/media/XENO/Dropbox/Software/Emacs/desktops/fos" nil)
(add-project ".emacs" "/media/XENO/Dropbox/Software/Emacs" nil)
